// Generated by scripts/sync_mobile_curated_preview.py from corpus/curated_v1.
// Metro only resolves files beneath mobile/, so this module intentionally has
// no static imports into the repository-level corpus directory.
import baseFixture from '../../fixtures/curated_v1/mobile_preview_fixture.json';
import turnOfTheScrew from '../../fixtures/curated_v1/turn_of_the_screw_pages.json';
import hazlittTableTalk from '../../fixtures/curated_v1/hazlitt_table_talk_pages.json';
import aRebours from '../../fixtures/curated_v1/a_rebours_pages.json';
import lesDiaboliques from '../../fixtures/curated_v1/les_diaboliques_pages.json';
import niebla from '../../fixtures/curated_v1/niebla_pages.json';
import lucesDeBohemia from '../../fixtures/curated_v1/luces_de_bohemia_pages.json';
import elDoncel from '../../fixtures/curated_v1/el_doncel_pages.json';
import { BookfinContentBlock } from '../../types/api';

type CorpusPage = {
  page_sequence_number: number;
  content_hash: string;
  blocks: BookfinContentBlock[];
};

type CorpusWork = {
  work_id: string;
  author: string;
  title: string;
  language: string;
  pages: CorpusPage[];
};

export interface CuratedPreviewSample {
  id: string;
  workId: string;
  author: string;
  title: string;
  language: string;
  pageSequenceNumber: number;
  blocks: BookfinContentBlock[];
  typographicalFeatures: string[];
  reviewRequired?: boolean;
}

const fixture = baseFixture as {
  samples: Array<{
    id: string;
    work_id: string;
    author: string;
    title: string;
    language: string;
    page_sequence_number: number;
    blocks: BookfinContentBlock[];
    typographical_features: string[];
  }>;
};

function sampleFromPage(
  workSource: unknown,
  id: string,
  features: string[],
  reviewRequired = false
): CuratedPreviewSample {
  const work = workSource as CorpusWork;
  // The sync script writes exactly one selected, unmodified V2 page per file.
  const page = work.pages[0];
  return {
    id,
    workId: work.work_id,
    author: work.author,
    title: work.title,
    language: work.language,
    pageSequenceNumber: page.page_sequence_number,
    blocks: page.blocks,
    typographicalFeatures: features,
    reviewRequired,
  };
}

const fixtureSamples: CuratedPreviewSample[] = fixture.samples.map((sample) => ({
  id: sample.id,
  workId: sample.work_id,
  author: sample.author,
  title: sample.title,
  language: sample.language,
  pageSequenceNumber: sample.page_sequence_number,
  blocks: sample.blocks,
  typographicalFeatures: sample.typographical_features,
  reviewRequired:
    sample.work_id === 'es-valle-inclan-luces-de-bohemia' ||
    sample.work_id === 'es-unamuno-niebla',
}));

const laParureHyphenationFixture = fixtureSamples.find((sample) => sample.workId === 'fr-maupassant-la-parure');

export const poliphiliTypographicalSpecimen: CuratedPreviewSample = {
  id: 'fixture-dev-poliphili-specimen',
  workId: 'dev-poliphili-specimen',
  author: 'Alde Manuce & Stanley Morison',
  title: 'Spécimen — Poliphili Roman & Italique',
  language: 'fr',
  pageSequenceNumber: 1,
  typographicalFeatures: [
    'font_specimen',
    'roman_vs_italic_same_line',
    'accents_fr',
    'accents_es',
    'punctuation_and_quotes',
  ],
  blocks: [
    {
      type: 'heading',
      level: 2,
      spans: [{ text: 'Spécimen Typographique Poliphili' }],
    },
    {
      type: 'paragraph',
      spans: [
        { text: 'Roman pur : L’éternité résonne d’une voix claire et limpide. ' },
        { text: 'Italique véritable : L’éternité résonne d’une voix claire (sans synthèse artificielle).', italic: true },
      ],
    },
    {
      type: 'paragraph',
      spans: [
        { text: 'FR Accents & Ligatures : ' },
        { text: 'é è ê ë à â î ï ô ù û ü ç œ æ — « Où l’âme s’élève au-delà du rêve ? »' },
      ],
    },
    {
      type: 'paragraph',
      spans: [
        { text: 'ES Acentos y Signos : ' },
        { text: '¿Quién vendrá mañana? ¡Qué alegría tan sublime! — á é í ó ú ü ñ.' },
      ],
    },
    {
      type: 'paragraph',
      spans: [
        { text: 'EN Dialogue & Em-dash : ' },
        { text: '“It is a truth universally acknowledged—” he whispered softly.' },
      ],
    },
    {
      type: 'paragraph',
      spans: [
        { text: 'Même ligne : Roman régulier / ' },
        { text: 'Italique côte à côte / ', italic: true },
        { text: 'Gras / ', bold: true },
        { text: 'Gras & Italique.', bold: true, italic: true },
      ],
    },
  ],
};

/** All content comes from Curated V1. REVIEW statuses remain human-only. */
export const curatedPreviewSamples: CuratedPreviewSample[] = [
  poliphiliTypographicalSpecimen,
  ...fixtureSamples,
  ...(laParureHyphenationFixture ? [{
    ...laParureHyphenationFixture,
    id: 'fixture-fr-la-parure-hyphenation',
    title: 'La Parure — césure FR',
    typographicalFeatures: [...laParureHyphenationFixture.typographicalFeatures, 'hyphenation_probe', 'long_french_words'],
  }] : []),
  sampleFromPage(turnOfTheScrew, 'page-en-turn-of-the-screw-italic', ['real_page', 'italic', 'long_prose']),
  sampleFromPage(hazlittTableTalk, 'page-en-hazlitt-table-talk-verse', ['real_page', 'verse', 'preserved_line_breaks']),
  sampleFromPage(aRebours, 'page-fr-a-rebours', ['real_page', 'heading', 'french_accents', 'long_prose']),
  sampleFromPage(lesDiaboliques, 'review-fr-barbey-les-diaboliques', ['REVIEW', 'real_page', 'preface_or_warning', 'narrative'], true),
  sampleFromPage(elDoncel, 'page-es-larra-el-doncel', ['real_page', 'spanish', 'long_prose', 'four_tomes_repaired']),
  sampleFromPage(niebla, 'review-es-unamuno-niebla', ['REVIEW', 'real_page', 'prologue_victor_goti', 'register_changes'], true),
  sampleFromPage(lucesDeBohemia, 'review-es-valle-inclan-luces-de-bohemia', ['REVIEW', 'real_page', 'theatre', 'stage_directions', 'dialogue'], true),
];
